### ISSUE TITLE
Testing in Laravel

### ISSUE THREAD

**Issue by stefnats** [ssi-anik/amqp#15]
Hey,

is there a way i can use this library in my feature tests in Laravel just like `Queue::fake()`?
If not, are there plans to implement it?

Thanks for your easy-to-use wrapper :)

**Comment by ssi-anik** [comment]
Hi, Thanks for the appreciation. Firstly, no you can't use anything like `Queue::fake` yet. I barely write tests, cause I lack this knowledge. It's still in my plan but don't know when I can complete this. But I'd like to request, if you're good at it, please send a PR and I'd be happy to merge.

Thanks.

**Comment by stefnats** [comment]
Almost a year later, i made the PR :)
