### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by insanebits** [ssi-anik/amqp#17]
Currently only php 7 is supported and php-amqplib already seems to support php 8, so there shoudn't be any big issues with the upgrade. 

**EDIT:**

It seems the issue is amqplib being locked at 2.9 which does not support PHP 8. 

There was another related issue which was closed:

https://github.com/ssi-anik/amqp/issues/16

**Comment by kiwina** [comment]
Where are you getting php7 support only? i got it installed on 8 without any problems

**Comment by insanebits** [comment]
I'm not sure how but according to packagist: https://packagist.org/packages/anik/amqp

php-amqplib/php-amqplib: ^2.9 !=2.12.0

Where amqplib: https://packagist.org/packages/php-amqplib/php-amqplib#v2.12.3

Is locked to php `<8.0`

This means that version 3.0 is not allowed and thus only php 7 is supported.

**Comment by nicopenaredondo** [comment]
@kiwina  how did you install it using PHP 8 ? i'm getting similar error with @insanebits

**Comment by ssi-anik** [comment]
Sorry guys to reply this late. I will check the PR sent by insanebits and add changes if required accordingly and inform here.

**Comment by ssi-anik** [comment]
Merged @insanebits 's PR #18. Tagged with `v1.6`. Thanks all.
