### ISSUE TITLE
PhpAmqpLib\Exception\AMQPConnectionClosedException: Broken pipe or closed connection in ....

### ISSUE THREAD

**Issue by nicopenaredondo** [ssi-anik/amqp#19]
Hi guys, anyone encountered this error message while using this package ?

**Comment by ssi-anik** [comment]
Seems like your RabbitMQ connection got disconnected somehow. when you encounter the issue, check if the mq was alive or not.

**Comment by nicopenaredondo** [comment]
@ssi-anik  After several minutes of idling. Once ive tried to publish another message this error occurs.

**Comment by nicopenaredondo** [comment]
Any idea on how to check if it was alive in PHP ?

**Comment by ssi-anik** [comment]
I don't have any solution right now. But you can check https://github.com/php-amqplib/php-amqplib/issues/706 or google it.
Also don't forget to share your solution here in case someone reaches here will find the solution too.
