### ISSUE TITLE
Support for Laravel 6.x

### ISSUE THREAD

**Issue by arcifius** [ssi-anik/amqp#2]
Hello!
I was looking around for some way to use rabbitMQ with Laravel more conveniently way and found your repo!
I've tried to use it with Laravel 6.x but got a compatibility error, do you have any plans for this support?
"- anik/amqp v1.1 requires illuminate/container ^5.8"

**Comment by ssi-anik** [comment]
Sorry for replying late. Okay, I will try to release ASAP. but if you want you can send me PR by changing the composer.json. Things shouldn't break I assume.

**Comment by ssi-anik** [comment]
@arcifius just published `v1.2` with laravel 6.x compatible.
