### ISSUE TITLE
Is there a way to create binding dynamically on publish? 

### ISSUE THREAD

**Issue by dlnsk** [ssi-anik/amqp#9]
Is there a way to create binding dynamically on publish?

**Comment by ssi-anik** [comment]
In my understanding, if you want to publish a message, all you need is the exchange. If you don't start listening from a queue connected to that exchange, the message will be lost. So, dynamically creating an exchange to publish a message can mean two things.
1. You want to create the exchange dynamically and listen from that exchange dynamically, then it's okay.
2. If you create an exchange dynamically and don't listen to that exchange, it'll be lost. So doesn't make sense IMO.
